FFImageLoading.Common/Work/WorkScheduler.cs
FFImageLoading.Droid/Work/ImageLoaderTask.cs

Also added additional null checks in some methods

Allow empty path

---

FFImageLoading.Touch/TaskParameterExtensions.cs
FFImageLoading.Touch/Work/ImageLoaderTask.cs
samples/ImageLoading.Forms.Sample/Droid/FFImageLoading.Forms.Sample.Droid.csproj
samples/ImageLoading.Forms.Sample/Droid/packages.config
samples/ImageLoading.Forms.Sample/iOS/packages.config

Please test it, if it’s working for you.

Fade animation support on iOS (untested)

---

Makefile

This commit fixes 'make package'

Update Makefile for renamed nuspecs

---

source/FFImageLoading.Cross/MvxImageLoadingView.cs

Useful when using AutoLayout when we don´t need to specify CGRect

Added default constructor

---

source/FFImageLoading.Windows.nuspec
source/Xamarin.FFImageLoading.Forms.nuspec
source/Xamarin.FFImageLoading.Transformations.nuspec
source/Xamarin.FFImageLoading.nuspec

Updated paths to be nuspec spec compliant
Combined Windows nuspec with main nusepc
Refactored dependencies to be a little cleaner

Fixed for Nuget package generation

---

source/FFImageLoading.Transformations.Droid/ColorSpaceTransformation.cs

This will ensure that images with transparency will be allowed to perform color transformations on Android

Added support for transparency images

---

source/FFImageLoading.Forms/ColorExtensions.cs

Creating the extension for Xamarin.Forms.Color object to allow easy creation of float array for color transformations, this also has the optional parameter of brightness to be adjustable.

Creating extension for Color object

---

source/FFImageLoading.Forms.WinRT/CachedImageRenderer.cs

This issue will hopefully address FFImageLoading issue https://github.com/luberda-molinet/FFImageLoading/issues/273

Possible fix for #273

---

FFImageLoading.sln
source/FFImageLoading.Common/Work/WorkScheduler.cs
source/FFImageLoading.Windows/FFImageSourceBinding.cs

The main problem seems the "async void" method TakeFromPendingTasksAndRun.
References:
- https://msdn.microsoft.com/en-us/magazine/jj991977.aspx --> Avoid Async Void
- http://a.co/bIIBnDF -->see pages 582,583: long-running tasks
- http://a.co/aG479K7 --> see pages 56,57: asynchroous methods
Note
Sorry for the changes to the sln files. I don't know how to exlude them

Possible fix for #424

---

source/FFImageLoading.Shared/Helpers/MD5Helper.cs
source/FFImageLoading.Windows/Helpers/MD5Helper.cs

See #506, this solves a rare issue with wrong images being loaded

MD5CryptoServiceProvider is not thread safe

---

source/FFImageLoading.Cross/MvxImageLoadingView.cs

Added support for the android.resource schema when working against the DataLocationUri property.

android.resource schema support.

---

source/FFImageLoading.Droid/Helpers/PlatformPerformance.cs
source/FFImageLoading.Shared/EmptyPlatformPerformance.cs
source/FFImageLoading.Shared/FFImageLoading.Shared.projitems
source/FFImageLoading.Shared/ImageService.cs
source/FFImageLoading.Touch/Helpers/PlatformPerformance.cs

Fix for https://github.com/luberda-molinet/FFImageLoading/issues/418

Fix crashing on Xamarin Designer

---

source/FFImageLoading.Common/Config/Configuration.cs
source/FFImageLoading.Common/Work/TaskParameter.cs
source/FFImageLoading.Droid/Work/PlatformImageLoadingTask.cs
source/FFImageLoading.Touch/Extensions/NSDataExtensions.cs
source/FFImageLoading.Touch/Work/PlatformImageLoaderTask.cs
source/FFImageLoading.Windows/Extensions/ImageExtensions.cs
source/FFImageLoading.Windows/Work/PlatformImageLoaderTask.cs

implement AllowUpscale

---

source/FFImageLoading.Windows/Cache/SimpleDiskCache.cs

Users of the API may want their disk cache somewhere other than ApplicationData.Current.TemporaryFolder.

Issue #667 Allow for specifying root of cache on Windows SimpleDiskCache

---

source/FFImageLoading.Svg.Shared/SkSvg.cs

Read styles within defs tag

---

source/FFImageLoading.Shared.IosMac/Extensions/PImageExtensions.cs

use scale factor of device

---

source/FFImageLoading.Droid/Decoders/GifDecoder.cs

Daniel, I think this oughta do it.  Tested with both static and animated GIFs and change seems to be working in both cases.  Sorry this took so long to push up.  Cheers!  
Dan Waters

Bugfix android gif image information

---

source/FFImageLoading.Forms/CachedImage.cs

Reflection is used for compatibility with older XF versions.

Fix for issues with non-default visual style

---

source/FFImageLoading.Droid/Decoders/GifDecoder.cs
source/FFImageLoading.Droid/Extensions/StreamExtensions.cs
source/FFImageLoading.Droid/FFImageLoading.Droid.csproj
source/FFImageLoading.Droid/packages.config

Addresses issue 1257
Uses third party package Karamunting.Android.BumpTech.GlideGifDecoder.4.9.0 and replace references where necessary
Added Stream to byte[] extension function

Use third party android gif decoder

---

.gitignore
source/FFImageLoading.Cross/MvxCachedImageView.cs

split ImageLoader creation and configuration
