luberda-molinet/FFImageLoading

FFImageLoading.Forms.Droid/CachedImageRenderer.cs
FFImageLoading.Forms.Droid/CachedImageView.cs
FFImageLoading.Forms.Droid/FFImageLoading.Forms.Droid.csproj
FFImageLoading.Forms.Droid/Resources/AboutResources.txt
FFImageLoading.Forms.Droid/Resources/values/Strings.xml
FFImageLoading.Forms.Droid/packages.config
FFImageLoading.Forms.Touch/CachedImageRenderer.cs
FFImageLoading.Forms.Touch/FFImageLoading.Forms.Touch.csproj
FFImageLoading.Forms.Touch/Properties/AssemblyInfo.cs
FFImageLoading.Forms.Touch/packages.config
FFImageLoading.Forms/CachedImage.cs
FFImageLoading.Forms/FFImageLoading.Forms.csproj
FFImageLoading.Forms/Properties/AssemblyInfo.cs
FFImageLoading.Forms/packages.config
FFImageLoading.sln

Xamarin.Forms `Image` class replacement which uses FFImageLoading. 
You have to initialize it in you platform specific project after `Xamarin.Forms.Init` method:
`CachedImageRenderer.Init();`
*Please test iOS version (can't build it now).*

Added Xamarin.Forms iOS / Android support

---

FFImageLoading.Common/Work/LoadingResult.cs
FFImageLoading.Common/Work/TaskParameter.cs
FFImageLoading.Droid/FFImageLoading.Droid.csproj
FFImageLoading.Droid/Work/ImageLoaderTask.cs
FFImageLoading.Droid/Work/StreamResolver/ApplicationBundleStreamResolver.cs
FFImageLoading.Droid/Work/StreamResolver/CompiledResourceStreamResolver.cs
FFImageLoading.Droid/Work/StreamResolver/FilePathStreamResolver.cs
FFImageLoading.Droid/Work/StreamResolver/IStreamResolver.cs
FFImageLoading.Droid/Work/StreamResolver/ResourceIdentifiersCache.cs
FFImageLoading.Droid/Work/StreamResolver/StreamResolverFactory.cs
FFImageLoading.Droid/Work/StreamResolver/UrlStreamResolver.cs
FFImageLoading.Shared/ImageService.cs
samples/ImageLoading.Sample/Config.cs
samples/ImageLoading.Sample/ImageLoading.Sample.csproj
samples/ImageLoading.Sample/PictureAdapter.cs

Hi,
I'm using MvvmCross and needed drawable resource to be placeholder. Right now, I would need to add the desired placeholder in Assets folder and set build action, which doesn't feel "native". I've extracted the code for resolving `Stream` object from path and source type into `IStreamResolver` implementations.
Implementation for `ApplicationBundle` type gets `Stream` by converting string representation of resource into integer and then gets `Stream` object by calling `Context.Resources.OpenRawResource (resourceId)`.
Example is shown in `ImageLoading.Sample` project (i.e. notice change in `Config.LoadingPlaceholderPath`).
Feel free to ask any question.

Refactor GetStreamAsync & change strategy for getting Stream of ApplicationBundle source type

---

FFImageLoading.Transformations.Droid/CircleTransformation.cs
FFImageLoading.Transformations.Droid/RoundedTransformation.cs
FFImageLoading.Transformations.Touch/CircleTransformation.cs
FFImageLoading.Transformations.Touch/RoundedTransformation.cs
FFImageLoading.Transformations.nuspec
FFImageLoading.Transformations/RoundedTransformation.cs

https://github.com/molinch/FFImageLoading/issues/62
- Unified behavior on both platforms (iOS/Android)
- `CircleTransformation` crops to rectangle by default
- `RoundedTransformation` crops to rectangle by default, but it can be changed (constructor with additional `cropWidthRatio` and `cropHeightRatio` parameters)

Fixes and refactorings for Circle / Rounded Transformations

---

FFImageLoading.Forms.Droid/CachedImageRenderer.cs
FFImageLoading.Forms.Touch/CachedImageRenderer.cs
FFImageLoading.Forms/CachedImage.cs
FFImageLoading.Touch/TaskParameterExtensions.cs
FFImageLoading.Touch/Work/ImageLoaderTask.cs
samples/ImageLoading.Forms.Sample/Droid/FFImageLoading.Forms.Sample.Droid.csproj
samples/ImageLoading.Forms.Sample/Shared/FFImageLoading.Forms.Sample.csproj
samples/ImageLoading.Forms.Sample/Shared/Pages/ListExamplePage.cs
samples/ImageLoading.Forms.Sample/iOS/FFImageLoading.Forms.Sample.iOS.csproj
samples/ImageLoading.Forms.Sample/iOS/packages.config

- Allow CachedImage to work as a drop-in replacement for the Xamarin.Forms.Image. In iOS, the bundled images are again correctly loading (synchronously) with the appropriate 1x, 2x or 3x version.
- Allow to Cancel pending download tasks, i.e. when a UITableViewCell has already left the screen before the download has finished.
- Only fade-in when image is not cached or loaded from a local resource.
The code changes were a bit quick and dirty, so feel free to refactor a bit! :)

Various small improvements

---

source/FFImageLoading.Common/Cache/IDownloadCache.cs
source/FFImageLoading.Common/Work/TaskParameter.cs
source/FFImageLoading.Droid/Work/StreamResolver/UrlStreamResolver.cs
source/FFImageLoading.Forms.Droid/CachedImageRenderer.cs
source/FFImageLoading.Forms.Touch/CachedImageRenderer.cs
source/FFImageLoading.Forms.WinRT/CachedImageRenderer.cs
source/FFImageLoading.Forms/CachedImage.cs
source/FFImageLoading.Shared/Cache/DownloadCache.cs
source/FFImageLoading.Touch/Work/DataResolver/UrlDataResolver.cs
source/FFImageLoading.Windows/FFImage.cs

on old devices, sometimes disk caching creates IO bounds which cause the
app slowness.
with this parameter we can avoid disk caching at all.

Add an option to avoid disk caching

---

source/FFImageLoading.Touch/Helpers/ScaleHelper.cs
source/FFImageLoading.Touch/Work/PlatformImageLoaderTask.cs

Not sure the exact technical reasons but "MainThreadDispatcher.Instance.Post" -> "DispatchQueue.MainQueue.DispatchSync(action)" was blocking when being called within the lazy load code. Bringing the code out of this into a method did the trick and the thread is no longer blocked.

fix for thread block

---

source/FFImageLoading.Common/Work/WorkScheduler.cs

We should bump up the priority on pending tasks if similar tasks have a higher priority.

Priority Bump on similar tasks

---

source/FFImageLoading.Touch/Helpers/ScaleHelper.cs

In iOS, every time we create a "PlatformImageLoaderTask" it is initialising the ScaleHelper. And for some reason the "Scale = UIScreen.MainScreen.Scale;" is blocking the main thread in certain situations. Because the scale won't change, we just need to initialize the ScaleHelper once.

ScaleHelper is now only initialized once

---

source/FFImageLoading.Cross/MvxImageLoadingView.cs

CleanParameters called before the makings of params, which sets
OnSuccess, OnError, and OnFinish to null, those Actions should be
conserved and set to null on dispose

OnSuccess, OnError, OnFinish always null

---

source/FFImageLoading.Windows/FFImage.cs

See Issue #501 for details. Basically this adds bindable properties to adjust the Horizonal and Vertical Alignment of the (inner) image in UWP (non-Forms).

Extra bindable properties for the UWP inner image

---

samples/ImageLoading.Forms.Sample/Shared/FFImageLoading.Forms.Sample.csproj
samples/ImageLoading.Forms.Sample/Shared/Pages/MenuPageModel.cs
samples/ImageLoading.Forms.Sample/Shared/Pages/SimpleGifPage.xaml
samples/ImageLoading.Forms.Sample/Shared/Pages/SimpleGifPage.xaml.cs
samples/ImageLoading.Forms.Sample/Shared/Pages/SimpleGifPageModel.cs
source/FFImageLoading.Touch/FFImageLoading.Touch.csproj
source/FFImageLoading.Touch/Helpers/GifHelper.cs
source/FFImageLoading.Touch/Work/PlatformImageLoaderTask.cs

This includes VERY basic GIF support for iOS with an included sample. I would imagine that as users needs for more advanced GIF support come up, we will see additional PR's.

Extremely BASIC iOS Gif support. (Have to start somewhere)

---

source/FFImageLoading.Windows/Extensions/ImageExtensions.cs

This fixes the issues described in https://github.com/luberda-molinet/FFImageLoading/issues/508. The issues is that, at least in release mode, return writeableBitmap is called before the code in MainThreadDispatcher.Instance.PostAsync is finished. Await does not help. I have encountered this way way before in Windows Phone 8 times (http://dotnetbyexample.blogspot.nl/2013/04/windows-phone-8-navigation-part_29.html) and I tried the same fix. It feels like a kludge, but it's a kludge that works. I have spent _quite_ some time on my last project figuring this out ;)

Fix for "Images don't show up in UWP release build"

---

source/FFImageLoading.Cross/MvxCachedImageView.cs

I tested this in Android, not sure if iOS would need additional work?
Covers issue #635

Embedded images can now be loaded with MvvmCross

---

source/FFImageLoading.Common/Concurrency/FastPriorityQueue/SimplePriorityQueue.cs
source/FFImageLoading.Common/Work/WorkScheduler.cs
source/Tests/FFImageLoading.Core.Tests/FFImageLoading/Concurrency/SimplePriorityQueue_Test.cs

This potentially fixes the race condition in #655 and definitely eats the exception so apps won't crash if it occurs.

Fix race condition in WorkScheduler

---

source/FFImageLoading.Svg.Shared/SkSvg.cs

For [this svg](https://haveibeenpwned.com/Content/Images/PwnedLogos/EpicGames.svg) in particular there was an exception while rendering. This was due to the lack of support of space separated value pairs in polygons and polylines.
In addition, there is an attribute in there: `display=“none”`. Added support for this by skipping rendering when detected

Added support for space separated polygon and polyline and display="none" attribute

---

source/FFImageLoading.Forms/CachedImage.cs

Fixes #545 (the remaining problem thereof) by scaling a `CachedImage` according to the rules of its `Aspect` property.
_NOTE: please excuse whitespace changes. I have an addin that strips superfluous whitespace. I can add it back in if it's a problem._

fix: don't scale image on XF if it fits available space

---

source/FFImageLoading.Transformations.Droid/FlipTransformation.cs

I propose to have same contracts between all supported platforms. FlipTransformation iOS and Windows implementations have default constructors and this allows us to have simple XAMLs. So we may use the same pattern and set default FlipTransforamtion type to Horizontal for Android as well.

Add default value for FlipTransformation in Droid

---

source/FFImageLoading.Svg.Shared/SvgDataResolver.cs

FFImageLoading.Svg.Platform.SvgDataResolver.cs#line 105
regex of ReplaceStringMap is not extracted correctly
the text "regex:" would be replaced in the SVG image instead of the regex matches.

Fix Replace regex substring bug

---

source/FFImageLoading.Cross/MvxCachedImageView.cs

This should fix the nullreference exception when binding the ImageStream property instead of ImagePath property.

Fix MvxCachedImageView NullReference when using ImageStream binding

---

source/FFImageLoading.Droid/Cache/LRUCache.cs

Fix crash reported [here](https://github.com/luberda-molinet/FFImageLoading/issues/1020).

Fix Cannot access a disposed object crash in LruCache.SizeOf method

---

source/FFImageLoading.Common/Helpers/PreserveAttribute.cs

Making annotation internal to avoid naming collision with existing annotation in namespace xamarin.forms.internals

Hide preserveattribute annotation

---

source/FFImageLoading.Forms.Droid/CachedImageFastRenderer.cs
source/FFImageLoading.Forms.Droid/CachedImageRenderer.cs

When parameterless constructors were made obsolete, the wrong constructor name ended up in the warning messages.

Fix obsolete warning messages

---

source/FFImageLoading.Svg.Shared/SKLinearGradient.cs
source/FFImageLoading.Svg.Shared/SKRadialGradient.cs
source/FFImageLoading.Svg.Shared/SkSvg.cs

The fill property is parsed from style but at rendering only the attribute was checked. Now it will consider both.
The clip-path property was only parsed if specified as an attribute. Now it will consider the attribute and style.
Gradients ignored the gradientTransform property which made some gradients render incorrectly. I added support to read it and apply it. However support for gradientUnits is still missing.
Some other minor syntax changes were also made.

Fix fill, clip-path and add gradientTransform

---

source/FFImageLoading.Droid/FFImageLoading.Droid.csproj
source/FFImageLoading.Forms.Droid/FFImageLoading.Forms.Droid.csproj

Seems that this was mistakenly bumped to 9.0 prematurely, and is causing compiler warnings.

Revert Droid TargetFrameworkVersion to v8.1

---

source/FFImageLoading.Forms.Droid/CachedImageFastRenderer.cs

This change adds clipping to the boundaries of the `ImageView` when the ScaleType is set to `CENTER_CROP`.
Fixes #1086, #1148.
Already fixed in Xamarin.Forms for the `Image` fast renderer.
https://github.com/xamarin/Xamarin.Forms/pull/4218

Enforce clipping on fast renderer when using AspectFill.

---

source/FFImageLoading.Shared/Cache/SimpleDiskCache.cs
source/FFImageLoading.Windows/Cache/SimpleDiskCache.cs

Delete the correct file when starting the SimpleDiskCache used on iOS / Android. Probably helps with the cache growing size (#500)

Fix clean on SimpleDiskCache

---

source/FFImageLoading.Shared.IosMac/Extensions/PImageExtensions.cs

Correct the compression quality value on iOS platform
"The compression quality to use, 0.0 is the maximum compression (worse quality), and 1.0 minimum compression (best quality)"
from: 
https://docs.microsoft.com/en-us/dotnet/api/uikit.uiimage.asjpeg?view=xamarin-ios-sdk-12#UIKit_UIImage_AsJPEG_System_nfloat_

Correct jpeg stream quality on iOS

---

source/FFImageLoading.Droid/Cache/ReuseBitmapDrawableCache.cs

Changed to force image that has been invalidated from cache to also be removed from the displayed cache and reuse pool.

Image Removal Logic Change

---

samples/Simple.TizenForms.Sample/Simple.TizenForms.Sample.cs
samples/Simple.TizenForms.Sample/Simple.TizenForms.Sample.csproj
source/FFImageLoading.Tizen/Decoders/BaseDecoder.cs
source/FFImageLoading.Tizen/Views/EvasImageContainer.cs
source/FFImageLoading.Tizen/Views/SharedEvasImage.cs
source/FFImageLoading.Tizen/Work/PlatformImageLoaderTask.cs

* Remove all interop call to the native libs
Fix : https://github.com/luberda-molinet/FFImageLoading/issues/1388
* Some Tizen devices was not allow interop call to the  builtins native libs, so can't run on these device
* Remove All interop call, so can run on all tizen devices, but some version of tizen does not support Downsample feature
No
No
Fix : https://github.com/luberda-molinet/FFImageLoading/issues/1388

[Tizen] Remove all interop call to the native libs

---

source/FFImageLoading.Svg.Shared/SkSvg.cs

I had a problem with the size of the embedded `data:image/png;base64` in SkSVG where the size is `100%` and not `pixel`.

Add width and height in percent handeling for ReadImage

---

source/FFImageLoading.Cross/MvxCachedImageView.cs

Feature
Users have to set `CustomDataResolver` to have working `CustomLoadingPlaceholderDataResolver` and `CustomErrorPlaceholderDataResolver`.
Users can set these data resolvers independently.
No
None
#1361

MvxCachedImageView : Set DataResolvers Independently

---

source/FFImageLoading.Svg.Shared/Helpers/CssHelpers.cs

Bug fix to deal with duplicated/grouped styles in SVG images
If duplicated keys are found, the execution will throw a "DuplicatedKeyFoundException"
SVG image files with duplicated/grouped style keys are supported now
Nor breaking change. Just biggger support to SVG images
Try to load a svg that has duplicated/grouped CSS styles
#1455

Add support to repeated/grouped CSS styles
